dogcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
]

dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update/', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete/', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})


class Dog(models.Model):

	name = models.CharField(max_length=100)
	breed = models.CharField(max_length=100)
	description = models.TextField(max_length=250)
	age = models.IntegerField()
	toys = models.ManyToManyField(Toy)
	def __str__(self):
		return self.name

	def get_absolute_url(self):

		return reverse('detail', kwargs={'dog_id': self.id})





MEALS = (
	('B', 'Breakfast'),
	('L', 'Lunch'),
	('D', 'Dinner'),
)


class Feeding(models.Model):
	date = models.DateField('Feeding date')
	meal = models.CharField(
		max_length=1,
		choices=MEALS, 
		default=MEALS[0][0])


	dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
	
	def __str__(self):

		return f"{self.get_meal_display()} on {self.date}"

	class Meta:
		ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

dogcollector/main_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Dog


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', {'dogs': dogs})


def dogs_detail(request, dog_id):
  dog = Dog.objects.get(id=dog_id)
  return render(request, 'dogs/detail.html', {'dog': dog})

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from .models import Dog, Toy
from .forms import FeedingForm



def add_feeding(request, dog_id):
  form = FeedingForm(request.POST)

  if form.is_valid():
    new_feeding = form.save(commit=False)
    new_feeding.dog_id = dog_id
    new_feeding.save()

  return redirect('detail', dog_id=dog_id)


class DogUpdate(UpdateView):
  model = Dog
  fields = ['breed', 'description', 'age']


class DogDelete(DeleteView):
  model = Dog
  success_url = '/dogs/'



class DogCreate(CreateView):
  model = Dog 
  

  fields = ['name', 'breed', 'description', 'age']



def home(request):
	return render(request, 'home.html')


def about(request):
	return render(request, 'about.html')


def dogs_index(request):

  dogs = Dog.objects.all()
  return render(request, 'dogs/index.html', {'dogs': dogs})


def dogs_detail(request, dog_id):
  dog = Dog.objects.get(id=dog_id)
  toys_dog_doesnt_have = Toy.objects.exclude(id__in = dog.toys.all().values_list('id'))

  feeding_form = FeedingForm()

  return render(request, 'dogs/detail.html', {'dog': dog, 'feeding_form': feeding_form, 'toys': toys_dog_doesnt_have})
class ToyList(ListView):
  model = Toy

class ToyDetail(DetailView):
  model = Toy

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys/'

def assoc_toy(request, dog_id, toy_id):
  Dog.objects.get(id=dog_id).toys.add(toy_id)
  return redirect('detail', dog_id=dog_id)

dogcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper teal lighten-2">
          <a href="#" class="brand-logo center">Dog Collector</a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="/dogs">View All My Dogs</a></li>
            <li><a href="/about">About</a></li>
          </ul>
        </div>
      </nav>
            
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
  </footer>
</body>
</html>

dogcollector/main_app/templates/dogs/detail.html
{% extends 'base.html' %}


{% block content %}

<h1>Dog Details</h1>

<div class="card">
	<div class="card-content">
		<span class="card-title">{{ dog.name }}</span>
		<p>Breed: {{ dog.breed }}</p>
		<p>Description: {{ dog.description }}</p>

		{% if dog.age > 0 %}
		<p>Age: {{ dog.age }}</p>

		{% else %}
		<p>Age: Puppy</p>

		{% endif %}

	</div>
</div>
{% endblock content %}

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}
    <h1>About the Dog Collector</h1>
    <hr/>
    <p>Hire the Dog Collector!</p>
    {% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dog Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
        <div class="nav-wrapper teal lighten-2">
          <a href="#" class="brand-logo center">Dog Collector</a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
            <li><a href="{% url 'dogs_create' %}">Add a Dog</a></li>
            <li><a href="{% url 'index' %}">View All My Dogs</a></li>
          </ul>
        </div>
      </nav>
            
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
  </footer>
</body>
</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Dog Details</h1>
<div class="row">
  <div class="col s6">
	<form action="{% url 'add_feeding' dog.id %}" method="post">
		{% csrf_token %}
		{{ feeding_form.as_p }}
		<input type="submit" class="btn" value="Add Feeding">
	  </form>
	  <br>
	  {% if dog.fed_for_today %}
		<div class="card-panel teal-text center-align">{{dog.name}} has been fed all meals for today</div>
	  {% else %}
		<div class="card-panel red-text center-align">{{dog.name}} might be hungry</div>
	  {% endif %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dogs_update' dog.id %}">Edit</a>
        <a href="{% url 'dogs_delete' dog.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in dog.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dog.name }}'s Toys</h3>
    {% if dog.toys.count %}
      {% for toy in cat.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' dog.id toy.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{dog.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
<script>
	const dateEl = document.getElementById('id_date');
	M.Datepicker.init(dateEl, {
	  format: 'yyyy-mm-dd',
	  defaultDate: new Date(),
	  setDefaultDate: true,
	  autoClose: true
	});
	const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Dog List</h1>
{% for dog in dogs %}
<div class="row">
  <a href="{% url 'detail' dog.id %}">
    <div class="col s12 m5">
      <div class="card-panel cyan lighten-4">
        <span class="card-title">{{ dog.name }}</span>
        <p>Breed: {{ dog.breed }}</p>
        <p>Description: {{ dog.description }}</p>
        {% if dog.age > 0 %}
          <p>Age: {{ dog.age }}</p>
        {% else %}
          <p>Age: Puppy</p>
        {% endif %}
      </div>
      </div>
    </div>
  </a>
  </div>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
	<h1>Home Page</h1>
{% endblock content %}
	

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Dog</h1>
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dog.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Dog</h1>
{% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}

  <form action="" method="post">

    {% csrf_token %}
    <table>

      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}